# Generated by Django 4.2.4 on 2023-10-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAbis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('contract_name', models.CharField(blank=True, max_length=50, null=True)),
                ('abi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract_abis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('contract_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoolCreationEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex', models.CharField(blank=True, max_length=50, null=True)),
                ('token0', models.CharField(blank=True, max_length=42, null=True)),
                ('token1', models.CharField(blank=True, max_length=42, null=True)),
                ('pair', models.CharField(blank=True, max_length=42, null=True)),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('logindex', models.IntegerField(blank=True, null=True)),
                ('transactionindex', models.IntegerField(blank=True, null=True)),
                ('transactionhash', models.CharField(blank=True, max_length=66, null=True)),
                ('address', models.CharField(blank=True, max_length=42, null=True)),
                ('blockhash', models.CharField(blank=True, max_length=66, null=True)),
                ('blocknumber', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pool_creation_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenReadFunctionsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(blank=True, max_length=50, null=True)),
                ('readfunc1', models.CharField(blank=True, max_length=50, null=True)),
                ('readfunc2', models.CharField(blank=True, max_length=50, null=True)),
                ('readfunc3', models.CharField(blank=True, max_length=50, null=True)),
                ('readfunc4', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'token_read_functions_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('isbasetoken', models.BooleanField(blank=True, null=True)),
                ('contract_deploy_time', models.DateTimeField(blank=True, null=True)),
                ('contract_deploy_block', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tokens',
                'managed': False,
            },
        ),
    ]
